apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rover
  name: rover
  namespace: ckad00017
spec:
  ports:
  - name: 81-80
    port: 81
    protocol: TCP
    targetPort: 80
  selector:
    app: ckad00017-deployment
    tier: dmz
  type: NodePort
status:
  loadBalancer: {}
