apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front
  name: front
  namespace: ckad00018
spec:
  containers:
  - image: nginx
    name: front
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
