apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: redis-test
  name: redis-test
  namespace: cpu-stress
spec:
  containers:
  - image: redis
    name: redis-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
